name: Release App

on:
  push:
    tags:
      - 'app-*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Caching
        uses: actions/cache@v2
        with:
          path: ${{ env.YARN_CACHE_FOLDER }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'

      - name: Install and Build 🔧
        run: |
          yarn --frozen-lockfile
          yarn build:app

      - name: Install SSH Client 🔑
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          SSH: true
          REPOSITORY_NAME: project-leek/project-leek.github.io
          BRANCH: master
          FOLDER: packages/app/dist
          CLEAN: true # Automatically remove deleted files from the deploy branch
